In [244]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import randint
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, recall_score, ConfusionMatrixDisplay
from sklearn.metrics import mean_squared_error
from sklearn.neighbors import KNeighborsClassifier

#Tree Visualization
from sklearn.tree import export_graphviz
from IPython.display import Image
import graphviz

import os

#Import dataset
dataset = pd.read_csv(r"C:\Users\sequi\CS235_Fall2023\diabetes_012_health_indicators_BRFSS2015.csv")
#print(dataset.head(10))

#information about the dataset
dataset.info()
dataset.columns[dataset.dtypes==object]
xaxis = []
range_xaxis = range(1,153683,1)
for i in range_xaxis:
    xaxis.append(i)


#plt.hist(x=xaxis,y=dataset['BMI'], bins='auto')
#plt.grid(axis='x', alpha=0.50)
#plt.xlabel('Survey Entries')
#plt.ylabel('BMI Records')
#plt.title('BMI Levels')

#plt.show()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99999 entries, 0 to 99998
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Diabetes_012          99999 non-null  int64
 1   HighBP                99999 non-null  int64
 2   HighChol              99999 non-null  int64
 3   CholCheck             99999 non-null  int64
 4   BMI                   99999 non-null  int64
 5   Smoker                99999 non-null  int64
 6   Stroke                99999 non-null  int64
 7   HeartDiseaseorAttack  99999 non-null  int64
 8   PhysActivity          99999 non-null  int64
 9   Fruits                99999 non-null  int64
 10  Veggies               99999 non-null  int64
 11  HvyAlcoholConsump     99999 non-null  int64
 12  AnyHealthcare         99999 non-null  int64
 13  NoDocbcCost           99999 non-null  int64
 14  GenHlth               99999 non-null  int64
 15  MentHlth              99999 non-null  int64
 16  PhysHlth              99999 non-null  int64
 17  DiffWalk              99999 non-null  int64
 18  Sex                   99999 non-null  int64
 19  Age                   99999 non-null  int64
 20  Education             99999 non-null  int64
 21  Income                99999 non-null  int64
dtypes: int64(22)
memory usage: 16.8 MB

In [246]:
#Finding missing values
dataset.isna().sum()
dataset.columns[dataset.isna().sum()!=0]
#Result= no missing values

Index([], dtype='object')

In [248]:
dataset

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0,1,1,1,40,1,0,0,0,0,...,1,0,5,18,15,1,0,9,4,3
1,0,0,0,0,25,1,0,0,1,0,...,0,1,3,0,0,0,0,7,6,1
2,0,1,1,1,28,0,0,0,0,1,...,1,1,5,30,30,1,0,9,4,8
3,0,1,0,1,27,0,0,0,1,1,...,1,0,2,0,0,0,0,11,3,6
4,0,1,1,1,24,0,0,0,1,1,...,1,0,2,3,0,0,0,11,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99994,0,0,1,1,28,0,0,0,1,1,...,1,0,2,0,3,0,1,9,6,8
99995,0,1,1,1,19,1,0,0,1,0,...,1,0,3,0,4,0,0,11,5,5
99996,0,1,1,1,25,1,0,1,1,1,...,1,0,2,0,10,1,0,13,4,5
99997,0,0,1,1,29,1,0,0,1,0,...,1,0,2,0,0,0,0,8,4,8
99998,0,1,1,1,24,1,0,0,0,0,...,1,0,1,0,0,0,0,12,3,3

In [250]:
#checking for any duplicates & total rows of duplicates
repeat = dataset[dataset.duplicated()]
print("# of duplicates is: ", len(repeat))

# of duplicates is:  6067

In [ ]:
#Changing the label names
dataset.rename(columns = {'Diabetes_012':'Dia_State',
                         'HighBP':'HiBloodPr',
                         'HeartDiseaseorAttack':'HeartDi_Attack',
                         'PhysActivity':'Phys_Act',
                         'HvyAlcoholConsump':'Alcohol_cons'}, inplace=True)
dataset

In [ ]:
##Splitting the data
X = dataset.drop('Dia_State', axis=1)
y = dataset['Dia_State']

y

In [ ]:
#Train-test split
# X = features, y = target, test_size = how big my test is going to be
#X_train & y_train are used for training
#X_test & y_test are used for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)#, random_state=42)

y_train

In [ ]:
#Shapes of my variables
X.shape

In [ ]:
#Create and train the Random Forest Model
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train, y_train)

In [ ]:
#Making a classifier prediciton and assiging values to y_pred
#This code used the predict method of a RandomForestClassifier object(rf_classifier)
#to make predictions on a set of data (X_test)
#the predicted values are then stored in variable y_pred
y_pred = rf_classifier.predict(X_test)

In [ ]:
#Evaluation of the model
#here we are checking the predictions against the actual values in the test set
#and count up how many the model got right
print("Accuracy: ", accuracy_score(y_test,y_pred))
#this code caculates the accuracy of a machine learning model's prediction
#by comparing the predicted values (y_pred) to the actual values (y_test)
#and then using the accuracy_score function from the scikit-learn to calculate
#the accuracy
print("\nClassification Report: \n", classification_report(y_test, y_pred))

#Confussion Matrix - 
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
ConfusionMatrixDisplay(confusion_matrix(y_test,y_pred)).plot()

In [ ]:
#Let's try another predicting model - KNN
#knn = KNeighborsClassifier(n_neighbors=5)
#y_pred = knn.predict(X_test)

#accuracy = accuracy_score(y_test,y_pred)
#precision = precision_score(y_test, y_pred)
#recall = recall_score(y_test,y_pred)

#print('The Accuracy is: ', accuracy)
#print('but wait, the precision is: ', precision)
#print('Ah! ok, and the recall is: ', recall)

In [ ]:
#using Mean Square Error (MSE)
mse = np.square(np.subtract(y_test,y_pred)).mean()

print('The Mean Square Error value is: ', mse)

In [ ]:
#Visualizing the results

for i in range(3):
    tree = rf_classifier.estimators_[i]
    dot_data = export_graphviz(tree,
                               feature_names=X_train.columns,
                               filled=True, max_depth=2,
                               impurity=False,
                               proportion=True)
    graph= graphviz.Source(dot_data)
    display(graph)

In [ ]:
#Hyperparameter Tuning
param_dist = {'n_estimators': randint(50,500),
             'max_depth': randint(1,20)}

#create a random forest classifier
rf = RandomForestClassifier()

#let's find the best hyperparameters
rand_search = RandomizedSearchCV(rf,
                                param_distributions = param_dist,
                                n_iter=5,
                                cv=5)

#fit the random search object to the data
rand_search.fit(X_train, y_train)

#this code is performing hyperparameter tuning for a random forest classifier
#using random search. First, a dictionary 'param_dist' is created with two
#hyperparameters to tune --> 'n_estimtarors' & 'max_detph'

In [ ]:
best_rf = rand_search.best_estimator_
print('Best hyperparameters: ', rand_search.best_params_)